# Generated by Django 5.0.6 on 2024-07-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_arcticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
