# Generated by Django 5.0.6 on 2024-07-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_is_published_alter_article_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('id',), 'verbose_name': 'статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='nothing', max_length=150, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
