# Generated by Django 5.0.6 on 2024-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Введите адрес', verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Введите Телефон', max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
