# Generated by Django 4.2.9 on 2024-08-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'permissions': [('cancel_is_publish', 'Can cancel is_publish'), ('can_change_product_description', 'Can change product description'), ('can_change_product_category', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
