# Generated by Django 4.2.9 on 2024-08-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'permissions': [('cancel_product_is_publish', 'Can cancel product is_publish'), ('can_change_product_description', 'Can change product description'), ('can_change_product_category', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
